# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ceb2ee324e79968b8c718811de506d82f83b761d4d29a89f2fd1123f8042737409c2b30607b9a22c5a8a0b3ec5411a177db3dca22df808c5060b73bd181ece80

test:
  secret_key_base: a72edccf00dd1d07c7214addba1a0c0f27d01b7099a07fd7b3e1c3c7eda2b7729089af680e3c887c0181967f13866983992fa53a6390e7fd57754ea972c90852

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
